apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadpihc4824-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadpihc4824-tenant-component
    app.kubernetes.io/part-of: loadpihc4824-tenant-app
  name: loadpihc4824-tenant-component
  namespace: loadpihc4824-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadpihc4824-tenant-component
    weight: null
status: {}
